#' Calculate fold change
#' 
#' Calculates the fold changes between samples for a given set of comparisons.
#' \code{plotFC} plots these fold changes as a bar graph.
#' 
#' 
#' @param tidydf Tidy dataframe of RFI values and their corresponding sample 
#'     and phenotype information. There should NOT be any technical replicates 
#'     (samples with the same sample name).
#' @param comparisons Dataframe with 2 columns and n rows, where n is the 
#'     number of desired comparisons. The fold change to be calculated will be
#'     column 2 divided by column 1, for each comparison/row.
#' @param log Single logical indicating whether the fold change should be 
#'     logged (base 2).
#' @param RFI_col Name of column containing RFI values, as string.
#' @param ABnames Optional argument. Merges full antibody names to the output
#'     dataframe.
#' @param fc_df Dataframe of fold changes generated by \code{calcFC}.
#' @param logged Single logical indicating whether the data have been logged
#' @param normalised Single logical indicating whether the data have been 
#'     normalised.
#' @param flip Single logical indicating whether the plot should be flipped
#' 
#' 
#' @importFrom assertthat assert_that
#' @importFrom dplyr mutate
#' @importFrom dplyr filter
#' @importFrom dplyr select
#' @import ggplot2
#' 
#' 
#' @describeIn calcFC Generates a dataframe of fold changes for each 
#'     comparison, with columns of corresponding names of samples compared and 
#'     their phenotype description.
#' @export 
calcFC <- function(tidydf, comparisons, log = FALSE, RFI_col = "RFI",
                   ABnames) {
  
  # check inputs
  assert_that(is.character(RFI_col), length(RFI_col) == 1,
              msg = "Check 'RFI_col' is a single string")
  
  assert_that(
    sum(c("X1", RFI_col, "AB") %in% colnames(tidydf)) == 3,
    msg = "Check 'data' has columns 'X1', 'AB' and your argument for 'RFI_col'")
  
  assert_that(is.logical(log), length(log) == 1,
              msg = "Check 'log' is single logical")
  
  assert_that(sum(
    c(comparisons[,1], comparisons[,2]) %in% tidydf$X1) == 2* nrow(comparisons),
    msg = "Check 'comparisons' df uses sample names")
   
  if (! missing(ABnames)){
    assert_that(
      sum(c("Antibody.Name","Ab.No.") %in% colnames(ABnames)) == 2,
      dim(ABnames)[2] == 2,
      msg = "Ensure columns 'Antibody.Name' and 'Ab.No.' exist in the 
            'ABnames' dataframe")
  }
  
  
  # convert to data.frame
  if (sum(class(tidydf) %in% "tbl_df") >= 1){
    tidydf <- as.data.frame(tidydf)
  }
  
  # obtain number of comparisons and ABs
  num_comparisons <- nrow(comparisons)
  num_ABs <- length(unique(tidydf$AB))
  
  # convert to wide format
  wide_df <- tidydf %>%
    select(X1, rlang::UQ(as.name(RFI_col)), AB) %>%
    tidyr::spread(value = rlang::UQ(as.name(RFI_col)), key = AB)
  
  # convert to matrix
  numeric_mat <- as.matrix(wide_df[,-1])
  rownames(numeric_mat) <- wide_df[,1]
  
  
  # calculate fold changes
  fc_mat <- matrix(nrow = num_comparisons, ncol = num_ABs)
  
  
  if (log){
    
    numeric_mat <- log2(numeric_mat)
  }
  
  for (i in 1:num_comparisons){
      
      cond1 <- comparisons[i,1]
      cond2 <- comparisons[i,2]
      
      if (log){
        
        # subtract if log
        fc_mat[i,] <- numeric_mat[rownames(numeric_mat) == cond2,] - 
          numeric_mat[rownames(numeric_mat) == cond1,]
        
      } else {
        
        # divide if raw
        fc_mat[i,] <- numeric_mat[rownames(numeric_mat) == cond2,] / 
          numeric_mat[rownames(numeric_mat) == cond1,]
        
      }
  }
  
  
  # convert back to df
  fc_df <- as.data.frame(fc_mat)
  
  ## add AB names as column names
  colnames(fc_df) <- colnames(wide_df)[-1]
      
  ## add conditions column
  condition <- vector(mode = "character", length = num_comparisons)
      
  for (i in 1:num_comparisons){
    
    condition[i] <- pheno[pheno$Lysate.ID == comparisons[i,2], "Condition"]
    
  }
  
  fc_df$Condition <- condition
  
  # add sample columns
  fc_df$Sample1 <- comparisons[,1]
  fc_df$Sample2 <- comparisons[,2]
      
  # change to long form
  fc_df <- fc_df %>%
    tidyr::gather(1:num_ABs, key = "AB", value = "FoldChange") 
  
  if (! missing(ABnames)){
    fc_df <- merge(fc_df, ABnames, by.x = "AB", by.y = "Ab.No.",
                all.x = TRUE, all.y = FALSE)
  }
  
  return(fc_df)
      
}


#' @describeIn calcFC Generates a barplot of fold changes for the desired
#'     comparisons.
#' @export
plotFC <- function(fc_df, comparisons, logged = FALSE, normalised = FALSE,
                   flip) {
  
  # check inputs
  assert_that(sum(c("Condition","Sample1","Sample2","AB", 
                                "FoldChange") %in% colnames(fc_df)) == 5,
                          msg = "'fc_df' should have on of each of the 
                                following columns: 'Condition',
                                'Sample1','Sample2','AB' & 'FoldChange'")
  
  assert_that(is.character(comparisons[,1]),
                          is.character(comparisons[,2]),
                          msg = "Check that 'comparisons' is of string type")
  
  assert_that(is.logical(logged), length(logged) == 1,
                          msg = "Check 'logged' is a single logical")
  
  assert_that(is.logical(normalised), length(normalised) == 1,
                          msg = "Check 'normalised' is a single logical")
  
  assert_that(is.logical(flip), length(flip) == 1,
                          msg = "Check 'flip' is a single logical")
  
  # colour blind friendly palette
  pal2 <- c("#000000", "#009E73", "#e79f00", "#9ad0f3", "#0072B2", 
            "#D55E00", "#CC79A7", "#F0E442")
  
  # create titles
  ylab <- "Fold Change"
  
  if (logged){
    
    ylab <- paste("Log2", ylab)
    
  }
  
  if (normalised){
    
    ylab <- paste("Normalised", ylab)
    
  }
  
  # number of comparisions
  num_comparisons <- nrow(comparisons)
  
  # main plot
  gg <- fc_df %>%
    mutate(sampComp = paste(Sample1, Sample2)) %>%
    filter(sampComp %in% paste(comparisons[,1], comparisons[,2])) %>%
    mutate(SampCond = paste(Sample2, Condition)) %>%
    ggplot(aes(y = FoldChange, x = Antibody.Name, fill = SampCond)) +
    geom_bar(stat = "identity", position = "dodge") +
    labs(title = "Fold change per antibody", x = "Antibody", 
         y = ylab) +
    scale_fill_manual(values = pal2[1:num_comparisons],
                      name = "Sample & Condition") +
    theme(plot.title = element_text(hjust = 0.5))
  
  
  if (flip){
    
    gg <- gg +
      coord_flip()
      
      
  } else {
    
    gg <- gg + 
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
  }

  return(gg)
  
}
